# Generated by Django 3.0.4 on 2020-03-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'permissions': [('special_status', 'Can read all draft')]},
        ),
    ]
