# Generated by Django 3.0.4 on 2020-03-16 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='change_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='改訂日'),
        ),
    ]
