# Generated by Django 3.0.4 on 2020-03-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0002_auto_20200318_0500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'permissions': [('special_status', 'Can read all drafts')]},
        ),
    ]
